name: CD

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: echo
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.id_rsa }} > ~/.ssh/id_rsa
          rsync -r -v --delete-after . cd@timephy.com:/private-backup/nginx/static/fp.timephy.com/
