name: CD

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: echo
        run: |
          mkdir -p ~/.ssh
          echo ${{ secrets.id_rsa }} > ~/.ssh/id_rsa
          ssh cd@timephy.com
          touch i_was_here

    env:
      DOCKER_REGISTRY: docker.pkg.github.com
      IMAGE_NAME: frustrated-physicists-backend
      # IMAGE_TAG: ${{ substring(github.ref, 11) }}
