name: CD

on:
  push:
    branches:
      - master
      - staging

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1

      - name: rsync
        run: |
          # compute deploy path
          BRANCH=${GITHUB_REF#refs/heads/}
          if [ $BRANCH == "master" ]; then
            DEPLOY_PATH=/private-backup/www/app.frust/
          elif [ $BRANCH == "staging" ]; then
            DEPLOY_PATH=/private-backup/www/app.frust.staging/
          fi
          echo $BRANCH
          echo $DEPLOY_PATH
          # set cd variables
          python3.6 .github/workflows/setup_version.py
          find *.html images scripts styles version.json -type f | python3.6 .github/workflows/setup_cache.py
          mkdir -p ~/.ssh
          # "" required, otherwise multiline secret is not treated correctly
          echo "${{ secrets.id_rsa }}" > ~/.ssh/id_rsa
          # rsync error if id_rsa is readable by other users
          chmod 700 ~/.ssh/id_rsa
          ssh-keyscan $SERVER > ~/.ssh/known_hosts
          # no / behind directories, otherwise only contents will be copied
          rsync -r -v --delete-after \
            *.html scripts styles images manifest.json sw.js version.json \
            cd@$SERVER:$DEPLOY_PATH
        env:
          SERVER: frust.app
